# creating a matrix with output columns based on input vector(N)

In [4]:
import numpy as np
x=np.array([10,20,30,40,60])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[   10000     1000      100       10        1]
 [  160000     8000      400       20        1]
 [  810000    27000      900       30        1]
 [ 2560000    64000     1600       40        1]
 [12960000   216000     3600       60        1]]


# Similar matrix is created using np.vander function in numpy

In [5]:
x=np.array([10,20,30,40,60])
N=5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[   10000     1000      100       10        1]
 [  160000     8000      400       20        1]
 [  810000    27000      900       30        1]
 [ 2560000    64000     1600       40        1]
 [12960000   216000     3600       60        1]]


# The determitant for both the matrixs is the same

In [6]:
np.linalg.det(matrix)

14400000000000.164

In [7]:
np.linalg.det(matrix1)


14400000000000.164